name: Auto Response to Issues

on:
  issues:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - name: Add a comment to the issue
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        body: |
          Thank you for oppening this issue. I will get back to you as soon as i come back from my vacation (09/01). 
